### ISSUE TITLE
GUI: tooltips with images broken

### ISSUE THREAD

**Issue by PaulStoffregen** [PaulStoffregen/Audio#148]
Somewhere we lost tooltips completely.  Then they were fixed, but the ones with images aren't working.

Here's what we're supposed to see.

![t1](https://cloud.githubusercontent.com/assets/965463/12236118/e1bc8c86-b82c-11e5-8cc8-1995c1357777.png)

Here's what we have now:

![t2](https://cloud.githubusercontent.com/assets/965463/12236124/ecef9ada-b82c-11e5-9ff7-c2ebfc546e52.png)

Not a super urgent bug since the right-side documentation is correct... but something to fix eventually.

**Comment by mamuesp** [comment]
Well, as I started debugging, the tooltips didn't work at all. I found a ToDo remark, that always the first <p> tag should be used as tooltip. I implemented that, and it worked fine on almost the whole node collection. But some nodes in the HTML help data aren't formatted in a consistent way, so the <p> tags had been wrapped in <div> tags and so on. This I could fix with a little change in the jQuery code, but if there are other <div> in the <p> tags, they are not included by jQuery, because they are not valid HTML. See this explanation: http://stackoverflow.com/questions/17021261/div-are-not-showing-inside-p-tags. So I think we should declare one valid format, evrything else is pilot's error.

**Comment by mamuesp** [comment]
Fast decision, pragmatic solution ... ;-)

**Comment by PaulStoffregen** [comment]
Turns out the old way that "worked" just grabbed the 3rd tag, which was a <p> in some and a <div> in others.  The TODO comment was old, from before some where converted to <div> so an image or more than paragraph could be used.

Eventually I want to create nice images for objects.....

**Comment by mamuesp** [comment]
Well, in this case ... always learning, what to keep and what not to keep in the code ... :-)
